[document]
vm=Document
;roles=authenticated
permissions=view-documents
heading='document-form-heading'

[document-search]
vm=DocumentSearch
;roles=authenticated
permissions=view-documents
heading='document-search-form-heading'

[document-list]
vm=DocumentList

[newsletters]
vm=Newsletters

[document-addenda]
vm=DocumentAddenda

