; used by TObjectContainer for instantiations
[tops.userfactory]
type ='Tops\cms\wordpress\WordpressUserFactory'
singleton=1

[tops.permissions]
type='Tops\db\TDBPermissionsManager'

[tops.language]
type='\Peanut\sys\PeanutTranslator'

[tops.mailer]
; Mailgun is an excellent 3rd party email service. See comments in pnut\src\Tops\mail\TMailgunMailer.php
; type='Tops\mail\TMailgunMailer'

; If Concrete5 mailer is used, disable 'core_mail' provider registration in application/config/app.php
; type='Tops\concrete5\Concrete5Mailer'

; use null mailer to disable mail service
;type='Tops\mail\TNullMailer'
;singleton=1

; PhpMailer is good for testing and CMSes without a good native mailer
; type='Tops\mail\TPhpMailer'
; use mailgun in production only
; type='Tops\mail\TMailgunMailer'
; If Concrete5 mailer is used, disable 'core_mail' provider registration in application/config/app.php
; type='Tops\concrete5\Concrete5Mailer'
; PhpMailer is good for CMSes without a good native mailer when not using a third party provider like Mailgun
; type='Tops\mail\TPhpMailer'
type='Tops\mail\TDevMailer'
singleton=1

[profiles.repository]
type='Peanut\contacts\db\model\repository\ContactsRepository';
; type='Peanut\users\db\model\repository\UserProfilesRepository'
singleton=1

; obsolete?
; [peanut.emailingsmanager]
; type='Peanut\QnutDirectory\db\DirectoryManager'
; type='Peanut\mailings\services\SubscriptionsManager'

[peanut.subscription_manager]
type='Peanut\contacts\db\model\repository\ContactsRepository'

;Enable this If peanut tables in the same db as the CMS (ConcreteCMS, WordPress)
; otherwise setup connections in config/database.in
;[tops.connections]
; ConcreteCMS
;type='Tops\concrete5\Concrete5ConnectionManager'
;  WordPress
;type='Tops\cms\wordpress\WordpressConnectionManager

[contacts.repository]
type='Peanut\contacts\db\model\repository\ContactsRepository'

[peanut.router]
type='Tops\cms\nutshell\NutshellRouter'

[services.inputhandler]
type='Tops\cms\wordpress\WordpressInputHandler'


