[settings]
default='bookstore'
; PDO error modes: ERRMODE_SILENT = 0; ERRMODE_WARNING = 1; ERRMODE_EXCEPTION = 2;
; errormode=2
[bookstore]
; server= defaults to localhost
database=bookstore
user=local_dba
pwd=2quake1652

[production]
; server= defaults to localhost
database=(database name here)
user=(user name here)
pwd=(password here)

[test]
; server=(servername here)
database=bookstore
user=local_dba
pwd=2quake1652