; copy as 'modelbuilder.ini' and make your changes.
[settings]
overwrite=1
namespace='Peanut\content\db'
prefixed=1
plural=1
; sourcePath='dev-tools/modelbuilder/output/src'
sourcePath='output/src'
; databaseKey defaults null
; databaseKey=tops-db

[tables]
pnut_content=1
; pnut_content_pages=1
; pnut_content_authors=1
;pnut_content_versions=1
;qcall_personalendorsements=1
; qcall_endorsements=1
; qcall_documents=1
; qcall_groupendorsements=1
;qcall_registrations=0
;qcall_contacts=0
;qcall_meetings=0
;qcall_gdcustomers=0
; qcall_errors=1
; qcall_contact_updates=1
;qcall_suppressions=1

[tops_contactlog]
entity=ContactLogEntry

[qnut_persons]
namespace=Peanut\QnutDirectory\db\model

[tops_mailboxes]
plural=2

[qnut_committee_statuses]
plural=2
namespace=Peanut\QnutCommittees\db\model

